### ISSUE TITLE
noob just started

### ISSUE THREAD

**Issue by schealex** [Akuukis/screeps#13]
hey guys, just started playing screeps, found your work here and wanted to test it.
mining transportation and upgrading seems to work great, but my spawn suddeltly stopped spawning creeps ( max number reached? ) and it is not constructing any buildings, do i need to wait for higher level?

regards,

alex

**Comment by Akuukis** [comment]
Hi Alex,

Thanks for looking into it! Unfortunately, code mismatch with documentation in most parts, and there are several obsolete and broken parts. In fact, the only code that **does** something (apart from filling memory and putting flags) is in [obselete.js](https://github.com/Akuukis/screeps/blob/master/src/obselete.js) file, which in its 290 lines is vary basic and doesn't do anything more than mine, transport, upgrade, and spawn creeps to replace old ones. Unfortunately I don't have enough time to dedicate to this project in order to implement all the fun stuff I envisioned and described in readme.

Have you checked out [screeps channel in slack](http://screeps.slack.com/)? It is quite active, and you can find me also there by the same nick if you have any questions.

**Comment by Akuukis** [comment]
I got back to this project. For you and others I made a 'legacy' branch that has everything non-working removed for easier understanding, while I will keep working on the big idea in 'dev' branch.
